### PR TITLE
Change the output path from /tmp to $HOME/.local/share

### PR DESCRIPTION
**Pull request by szlin**
@rigred @rhertzog 
I've changed the output path from /tmp to $HOME/.local/share due to security issues, please review it. 

Thanks the feedback from rhertzog.

### CODE REVIEW

**Comment by rigred** [comment]
With this change output will always be written to `/root/.local/share/sandsifter`
At least for the time being.

**Comment by rigred** [comment]
I will adapt the code to get the user that ran sudo.

**Comment by rigred** [comment]
Ok so checking for the parent user name of sudo is easily done but creates an additional headache in that I cannot simply assume the path of the $HOME directory to be /home. 

I will need to write additional code to work around that problem.

**Comment by rhertzog** [comment]
You can use `os.path.expanduser('~%s/.local/share/sandsifter' % os.environ.get('SUDO_USER', ''))`.

**Comment by rigred** [comment]
Tested it and it indeed works for odd username locations.
Handy snippet of code to have, thanks!

**Comment by rigred** [comment]
Later when I update the sifter to run only injector subprocess as root this will be much easier to deal with.

**Pull request merged**
