### PR TITLE
Issues from the Debian package of sandsifter

### PR DESCRIPTION
**Pull request by jpalecek**
Hello,

while using the Debian package of sandsifter, I discovered two problems which make it unusable. This merge request contains commits correcting them. More detailed info about them is in the commit messages.

Particularly, the problems are:
- [sandsifter fails to build on i386 due to wrong assembly](https://buildd.debian.org/status/fetch.php?pkg=sandsifter&arch=i386&ver=1.03-2&stamp=1547570894&raw=0)
- some builds, most notably the [current amd64 package](http://ftp.cz.debian.org/debian/pool/main/s/sandsifter/sandsifter_1.03-2_amd64.deb), just don't do anything. When you run sifter it just hangs and stops. This is due to the routines in the `inject` function not respecting the AMD64 ABI.

These commits fix those two problems. I tested them on i386 and amd64, however, I haven't tried them on kfreebsd (only linux).

Feel free to ask about the  particular decisions made when creating the commits.

### CODE REVIEW

**Comment by rigred** [comment]
Super stuff. 
I will test and review this so we can merge this as soon as possible for me. (Within next 2 days)

**Comment by jpalecek** [comment]
Thanks for your reply.

> I will test and review this so we can merge this as soon as possible for me. (Within next 2 days)

Please do! If you encounter any difficulties, I would be interested in the details so that I can possibly correct them. There's a clumsier, but maybe robuster approach especially to the second issue. I would also like to hear from @rene0 if it works on kfreebsd.

**Comment by rigred** [comment]
I've only been able to test on x86_64 hardware as yet and everything looks alright.
Sure the fix is not the most optimal solution but it's quite a bit better than before. 

With my i386 machines I've got some unexpected kernel/distro troubles to figure out.
But likely good to merge.

**Comment by rigred** [comment]
Manually merged.

**Pull request closed without merging**
